server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/themis?characterEncoding=utf-8&&SSL=false
    username: root
    password:
  http:
      multipart:
        max-file-size: 10Mb
        max-request-size: 10Mb
logging:
  config: classpath:logback.xml

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: tk.mapper.model.mapper
